- name: Configure Yum Repos
  ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install Erlang & Nodejs
  ansible.builtin.yum:
    name:
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
      - rabbitmq-server
    state: installed

- name: Start Rabbitmq Server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Configure Application User
  community.rabbitmq.rabbitmq-server:
    user: root
    password: roboshop123
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    vhost: /
    state: present
    tags: administrator

