- name: Setup Yum Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_16.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add a Application User
  ansible.builtin.user:
    name: roboshop

- name: Download & Extract Catalogue Contnet
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Remove Old catalogue Content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy catalogue Code
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
   become_user: roboshop
